<h2 class="title"><span>Relatórios</span></h2>
<br class="clear" />
<?php echo $this->render('partial/breadcrumbs.phtml'); ?>
<br class="clear" />
<div class="form-container">
    <h3 class="form-title alpha">Acompanhamento de Preço</h3>
    <br class="clear" />
    <?php echo $this->formPrice; ?>
</div>
<div class="form-container space4">
    <h3 class="form-title">Lorem ipsum dolor sit 1...</h3>
</div>
<div class="form-container space4">
    <h3 class="form-title">Lorem ipsum dolor sit 2...</h3>
</div>
<br class="clear" />