<div class="box menu-pr container_12">
    <ul>
        <li>&bull; <a href="<?php echo $this->url(array(), 'default', true); ?>">Início</a></li>
        <li>&bull; <a href="<?php echo $this->url(array('controller' => 'product'), 'default', true); ?>">Produtos</a></li>
        <li>&bull; <a href="<?php echo $this->url(array('controller' => 'shopping'), 'default', true); ?>">Feiras</a></li>
        <li>&bull; <a href="<?php echo $this->url(array('controller' => 'report'), 'default', true); ?>">Relatórios</a></li>
    </ul>
</div>